/****************************************************************/
/*    NAME: Charles Hoecker                                     */
/*    ACCT: cs032100                                            */
/*    FILE: BTMove.H                                            */
/*    ASGN: Final                                               */
/*    DATE: Wed May  4 23:19:01 1994                            */
/****************************************************************/

#ifndef BTMOVE_H
#define BTMOVE_H

#include "BTConfig.H"


#endif
