h50728
s 00000/00000/00000
d R 1.2 01/10/20 13:35:19 Codemgr 2 1
c SunPro Code Manager data about conflicts, renames, etc...
c Name history : 2 1 usr/src/widget/BTColor.H
c Name history : 1 0 src/widget/BTColor.H
e
s 00021/00000/00000
d D 1.1 01/10/20 13:35:18 bmc 1 0
c date and time created 01/10/20 13:35:18 by bmc
e
u
U
f e 0
t
T
I 1
/****************************************************************/
/*    NAME:                                                     */
/*    ACCT: cgh                                                 */
/*    FILE: BTColor.H                                           */
/*    ASGN:                                                     */
/*    DATE: Thu Sep 28 15:06:18 1995                            */
/****************************************************************/


#ifndef BTCOLOR_HEADER
#define BTCOLOR_HEADER

class BTColor {
public:

protected:
  BTColor() {}

};

#endif
E 1
