h34590
s 00000/00000/00000
d R 1.2 01/10/20 13:34:52 Codemgr 2 1
c SunPro Code Manager data about conflicts, renames, etc...
c Name history : 2 1 usr/src/btref/btcmdtab.H
c Name history : 1 0 src/btref/btcmdtab.H
e
s 00010/00000/00000
d D 1.1 01/10/20 13:34:51 bmc 1 0
c date and time created 01/10/20 13:34:51 by bmc
e
u
U
f e 0
t
T
I 1
#ifndef BTCMDTAB_H
#define BTCMDTAB_H

#include "BTConfig.H"

extern Command cmdtab[];
extern int CMDTABLEN;
extern int CMDMAXLEN;

#endif
E 1
