h36275
s 00000/00000/00000
d R 1.2 01/10/20 13:34:54 Codemgr 2 1
c SunPro Code Manager data about conflicts, renames, etc...
c Name history : 2 1 usr/src/btref/btglob.H
c Name history : 1 0 src/btref/btglob.H
e
s 00007/00000/00000
d D 1.1 01/10/20 13:34:53 bmc 1 0
c date and time created 01/10/20 13:34:53 by bmc
e
u
U
f e 0
t
T
I 1
#ifndef BTGLOB_H
#define BTGLOB_H

extern int hasglobchars(register char *pat);
extern int globmatch(register char *text, register char *pat);

#endif
E 1
