h05644
s 00000/00000/00000
d R 1.2 01/10/20 13:35:27 Codemgr 2 1
c SunPro Code Manager data about conflicts, renames, etc...
c Name history : 2 1 usr/src/game/BTDirs.H
c Name history : 1 0 src/game/BTDirs.H
e
s 00019/00000/00000
d D 1.1 01/10/20 13:35:26 bmc 1 0
c date and time created 01/10/20 13:35:26 by bmc
e
u
U
f e 0
t
T
I 1
#ifndef BTDIRS_H
#define BTDIRS_H

#define BT_SOUND_DIR	"/home/mws/share/BattleTris/sounds/" // Get rid of this!
#define BT_ART_DIR	"/home/mws/share/BattleTris/art/"   // Get rid of this!
#define BTDB_WEAPONS	"/home/mws/share/BattleTris/btweapons.db" // Get rid of this!
#define BTDB_WEAPONSP	"/home/mws/share/BattleTris/btweaponsp.db"// Get rid of this!

#define BTDB_PLANFILE	"/.btplan"
#define BTDB_NETWORK	"btnetwork"
#define BTDB_PLAYERS	"btplayers"

#define BTMD_PIDFILE	"btserverd.pid"
#define BTMD_LOGFILE	"btserverd.log"
#define BTMD_PIPENAM	".bt"

#define BTSD_LOGFILE	"btslaved"

#endif
E 1
