h47729
s 00000/00000/00000
d R 1.2 01/10/20 13:35:29 Codemgr 2 1
c SunPro Code Manager data about conflicts, renames, etc...
c Name history : 2 1 usr/src/game/BTMove.H
c Name history : 1 0 src/game/BTMove.H
e
s 00015/00000/00000
d D 1.1 01/10/20 13:35:28 bmc 1 0
c date and time created 01/10/20 13:35:28 by bmc
e
u
U
f e 0
t
T
I 1
/****************************************************************/
/*    NAME: Charles Hoecker                                     */
/*    ACCT: cs032100                                            */
/*    FILE: BTMove.H                                            */
/*    ASGN: Final                                               */
/*    DATE: Wed May  4 23:19:01 1994                            */
/****************************************************************/

#ifndef BTMOVE_H
#define BTMOVE_H

#include "BTConfig.H"


#endif
E 1
