/****************************************************************/
/*    NAME:                                                     */
/*    ACCT: cgh                                                 */
/*    FILE: BTColor.H                                           */
/*    ASGN:                                                     */
/*    DATE: Thu Sep 28 15:06:18 1995                            */
/****************************************************************/


#ifndef BTCOLOR_HEADER
#define BTCOLOR_HEADER

class BTColor {
public:

protected:
  BTColor() {}

};

#endif
