#ifndef BTDIRS_H
#define BTDIRS_H

#define BT_SOUND_DIR	"/home/mws/share/BattleTris/sounds/" // Get rid of this!
#define BT_ART_DIR	"/home/mws/share/BattleTris/art/"   // Get rid of this!
#define BTDB_WEAPONS	"/home/mws/share/BattleTris/btweapons.db" // Get rid of this!
#define BTDB_WEAPONSP	"/home/mws/share/BattleTris/btweaponsp.db"// Get rid of this!

#define BTDB_PLANFILE	"/.btplan"
#define BTDB_NETWORK	"btnetwork"
#define BTDB_PLAYERS	"btplayers"

#define BTMD_PIDFILE	"btserverd.pid"
#define BTMD_LOGFILE	"btserverd.log"
#define BTMD_PIPENAM	".bt"

#define BTSD_LOGFILE	"btslaved"

#endif
