h37284
s 00000/00000/00000
d R 1.2 01/10/20 13:34:58 Codemgr 2 1
c SunPro Code Manager data about conflicts, renames, etc...
c Name history : 2 1 usr/src/daemons/btslaved.H
c Name history : 1 0 src/daemons/btslaved.H
e
s 00010/00000/00000
d D 1.1 01/10/20 13:34:57 bmc 1 0
c date and time created 01/10/20 13:34:57 by bmc
e
u
U
f e 0
t
T
I 1
#ifndef BTSLAVED_H
#define BTSLAVED_H

#include "BTConfig.H"

class BTConfigFile;

extern BTConfigFile *g_conf;	// Pointer to configuration file object

#endif
E 1
