#!/usr/bin/env bash
#
# Regenerate the committed Apalache trace fixtures the Rust conformance harness
# replays (rust/bt-server/tests/traces/*.itf.json). Each generator model + .cfg has a
# TRAP invariant (a negated history var) so Apalache emits the SHORTEST trace that
# reaches the scenario; we copy that trace into the fixtures dir.
#
# Usage:
#   tla/regen-traces.sh                # regenerate (overwrite the committed fixtures)
#   tla/regen-traces.sh --check        # regenerate to a temp dir + diff vs committed;
#                                      #   nonzero exit if any fixture is STALE (for CI)
#
# Needs apalache-mc on PATH (or APALACHE_MC pointing at the binary) + Java 17+.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TRACES="$HERE/../rust/bt-server/tests/traces"
APALACHE="${APALACHE_MC:-apalache-mc}"

# We normalize Apalache's per-run timestamp out of each fixture with jq so committed
# files are stable (and --check is a real staleness gate, not a timestamp diff). Fail
# loudly if jq is missing rather than emitting an un-normalized fixture that --check
# would then flag as perpetually stale.
command -v jq >/dev/null 2>&1 || { echo "ERROR: jq is required (trace normalization)." >&2; exit 1; }
command -v "$APALACHE" >/dev/null 2>&1 || { echo "ERROR: apalache-mc not found (set APALACHE_MC)." >&2; exit 1; }

CHECK=0
[[ "${1:-}" == "--check" ]] && CHECK=1

# scenario:cfg:model  — the committed fixture filename is "<scenario>.itf.json".
SCENARIOS=(
  "bazaar_crossing:GenCross.cfg:Gen.tla"
  "weapon_then_cross:GenWeaponCross.cfg:Gen.tla"
  "reconnect_snapback:GenReconnect.cfg:Gen.tla"
  "two_bazaar_visits:GenTwoVisits.cfg:Gen.tla"
)

OUT_DIR="$TRACES"
if [[ "$CHECK" == "1" ]]; then
  OUT_DIR="$(mktemp -d)"
  trap 'rm -rf "$OUT_DIR"' EXIT
fi

stale=0
for entry in "${SCENARIOS[@]}"; do
  IFS=: read -r scenario cfg model <<< "$entry"
  echo ">> generating $scenario  (from $model / $cfg)"
  work="$(mktemp -d)"
  # Apalache writes its run dir under --out-dir; the trap invariant violation lands in
  # violation1.itf.json. --length is a safe upper bound on the shortest trap trace.
  ( cd "$HERE" && "$APALACHE" check --length=12 --out-dir="$work" \
      --config="$cfg" "$model" >/dev/null 2>&1 ) || true
  found="$(find "$work" -name 'violation1.itf.json' | head -1)"
  if [[ -z "$found" ]]; then
    echo "ERROR: no violation trace produced for $scenario — the trap invariant did not fire." >&2
    rm -rf "$work"
    exit 1
  fi
  # NORMALIZE: Apalache stamps a wall-clock timestamp into #meta.description on every
  # run; replace it with a stable marker so the committed fixtures don't churn each regen.
  fresh="$(jq '.["#meta"].description = "regenerated by tla/regen-traces.sh"' "$found")"
  rm -rf "$work"

  if [[ "$CHECK" == "1" ]]; then
    # STALENESS, robustly. Apalache's trace SELECTION is not deterministic — the Z3
    # backend may return a DIFFERENT (equally-short, equally-valid) trap trace across
    # runs, so a byte-diff of the whole trace would be FLAKY. What actually goes stale
    # when the model changes is the trace SHAPE: the variable set, their ITF types, and
    # the config params. We compare those (the schema), which catches the realistic
    # staleness — a renamed/retyped/added model variable the harness then can't map —
    # without false-flagging a mere re-pick of an alternative valid trace. (Per-state
    # CONFORMANCE of the actual committed trace is checked separately, and with teeth, by
    # the Rust `apply_input_conforms_to_every_tla_trace`.)
    schema() { jq -S '{vars: (.vars|sort), varTypes: .["#meta"].varTypes, params: (.params|sort)}'; }
    if ! diff -q <(printf '%s' "$fresh" | schema) \
                 <(schema < "$TRACES/$scenario.itf.json") >/dev/null 2>&1; then
      echo "STALE FIXTURE: $scenario.itf.json schema (vars/types/params) differs from the model." >&2
      echo "  committed:" >&2; schema < "$TRACES/$scenario.itf.json" >&2
      echo "  fresh:" >&2; printf '%s' "$fresh" | schema >&2
      stale=1
    fi
  else
    # Regen mode: overwrite the committed fixture with the fresh (normalized) trace.
    printf '%s\n' "$fresh" > "$OUT_DIR/$scenario.itf.json"
  fi
done

if [[ "$CHECK" == "1" && "$stale" == "1" ]]; then
  echo "One or more committed trace fixtures are stale; run tla/regen-traces.sh." >&2
  exit 1
fi
echo "done."
